source 'https://rubygems.org'

ruby '3.1.2'

gem 'rspec', '3.11.0', require: false
gem 'rspec_junit_formatter', '0.5.1', require: false
gem 'rubocop', '1.32.0', require: false
gem 'rubocop-rspec', '2.12.1', require: false
