name: pages 
on: [push]
jobs:
  build_pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1.111.0
        with:
          bundler-cache: true
          ruby-version: '3.1.2'
      - run: bundle config set --global clean true
      - run: bundle install
      - run: bundle exec jekyll build
      - run: touch docs/.nojekyll
      - uses: actions/upload-artifact@v3
        with:
          name: docs
          path: docs
  publish_pages:
    needs: build_pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: docs
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs


