name: build docs
on: [push]
jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1.111.0
        with:
          ruby-version: '3.1.2'
      - run: bundle install
      - run: bundle exec jekyll build
      - run: touch docs/.nojekyll
