name: main
on:
  - push
jobs:
  rubocop:
    strategy: 
      matrix:
        dir:
          - algebra
          - kanban
          - www
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup ruby
        uses: ruby/setup-ruby@v1.111.0
        with:
          bundler-cache: true
          ruby-version: '3.1.2'
          working-directory: ${{ matrix.dir }}
      - name: rubocop
        run: |
          cd ${{ matrix.dir }}
          bundle exec rubocop
  public:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup ruby
        uses: ruby/setup-ruby@v1.111.0
        with:
          bundler-cache: true
          ruby-version: '3.1.2'
          working-directory: www
      - name: jekyll build
        run: |
          cd www
          bundle exec jekyll build
      - name: upload public
        uses: actions/upload-artifact@v3
        with:
          name: www-public
          path: www/public
  deploy:
    needs: public
    if: ${{github.ref_name == 'main'}}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: downlod public
        uses: actions/download-artifact@v3
        with:
          name: www-public
          path: www/public
      - name: no jeykill processing by github
        run: touch www/public/.nojekyll
      - name: deploy public 
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: www/public

