name: www
on:
  - push
jobs:
  build_www:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1.111.0
        with:
          bundler-cache: true
          ruby-version: '3.1.2'
      - run: cd www
      - run: bundle config set path .bundle
      - run: bundle install
      - run: bundle exec jekyll build
      - run: touch public/.nojekyll
      - uses: actions/upload-artifact@v3
        with:
          name: www/public
          path: www/public
  deploy_www:
    needs: build_pages
    if: ${{github.ref_name == 'main'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: www/public
          path: www/public
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: www/public


